### ISSUE TITLE
User can search for Pokemon #1

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/pokemon-catcher#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for Pokemon 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can type the name of a Pokemon in an empty search box and click the “Submit” button to switch to a new page showing the Pokemon they inputted along with a photo and a list of all the stats associated with the Pokemon.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/140816723-25daaec8-d96e-47a9-be1c-27c049086491.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the header tab at the top in Html with proper CSS
- [x] Create body page content with header, empty search tab , submit button, and generate random Pokemon button. CSS included
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] If user doesn't type anything in, a pop up will appear notifying user.
- [x] If user types in a Pokemon that doesn't exist, a popup will appear notifying user.
- [x] If user types in a Pokemon that does exist, a new page will be shown displaying the Pokemon with all of it's stats
- [x] User can click button to search for another Pokemon
- [x] Fix all bugs
- **Clean Up**
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
