### ISSUE TITLE
User cannot add duplicate Pokemon #6

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/pokemon-catcher#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User cannot add duplicate Pokemon

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If user clicks "Add to Collection" button when they already have the Pokemon in their collection, a modal will appear saying "Pokemon is already in your Collection". User can they click "Okay" to exit modal.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/141705680-9d8d233e-c8d7-4525-864f-05ae3a1c1a42.png)
![image](https://user-images.githubusercontent.com/90541276/141705956-c824ccb4-fd8a-4856-a656-d32cf614769f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update "Add to Collection" event listener to not add Pokemon to collection if it already exists in collection.
- [x] Create notification modal saying "Pokemon already in Collection" and a "Okay" Button.
- [x] Update 'Add to Collection' Event Listener to display noticaition modal once clicked. 
- [x] Add event listener to "Okay " button to close modal.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
