### ISSUE TITLE
User can sort Collection in alphabetical order #7

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/pokemon-catcher#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sort Collection in alphabetical order
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the collection page, a select form element will be displayed in the top right. If clicked, an option named "A-Z" will appear. If the "A-Z" option is clicked, the Pokemon in the collection will be rearranged in Alphabetical order.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/141722490-4fc24708-0a8f-4503-b8d4-fe3506e7f30e.png)
![image](https://user-images.githubusercontent.com/90541276/141722610-987311d8-a551-4051-95c1-f2a00c1c8219.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the select form element in HTML
- [x] Style in CSS
- [x] Query Dom for A-Z option. Add an event listener to A-Z option. Once clicked, use .sort() to organize data.entries.name in alphabetical.  
- **Clean Up**
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
