### ISSUE TITLE
User can sort Collection from Z-A #8

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/pokemon-catcher#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sort Collection from Z-A

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the Collection page, there will be a option select box. Once clicked, user can then select the "Sort By: Z-A" option to reorganize collection from reverse alphabetical order.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/142481370-7f1a2520-23a6-4bd1-ad74-70444a5b1bbf.png)
![image](https://user-images.githubusercontent.com/90541276/142481482-1a06bb4e-9a7b-4eae-958c-7122742b39f7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create select option for reverse alphabetical order in HTML
- [x] Query Dom for option and add change event listener. Once fired, sort Pokemon in Collection from Z-A 
- **Clean Up**
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
