### ISSUE TITLE
User can sort Collection by Oldest First #9

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/pokemon-catcher#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sort Collection by Oldest First 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the Collection page, the user can click on a select option tab which displays multiple sorting options. If user clicks "Sort by: Oldest First", then the Pokemon in the collection will be reorganized with the oldest entry first and newest entry last.
## 🖼️ Wireframes

> ##### Wireframe screenshots

![image](https://user-images.githubusercontent.com/90541276/142508493-f6aa77d2-686f-4b33-91de-f706d4208e1b.png)
![image](https://user-images.githubusercontent.com/90541276/142508538-cf5c682b-63bd-4321-b1e8-cebdd88e843f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create select option titles 'Sort by: Oldest First'.
- [x] In Event listener for the select option element, add an If statement to check if event.target.value is strictly equal to the name of created option.
- [x] In if statement body, clear page using .innerHTML and reverse order of data.entries using .reverse()
- **Clean Up**
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
