### ISSUE TITLE
User can view total in collection

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/pokemon-catcher#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view number of Pokemon in Collection

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the Collection page, the total number of Pokemon in the Collection will be displayed on the left side of the title.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/142515503-3ec45221-5274-48a5-9091-da190f87ed1e.png)
![image](https://user-images.githubusercontent.com/90541276/142516138-28085dfd-fab6-40ec-a6a9-dd0947e18e52.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create p tag element in HTML
- [x] Style p tag in CSS
- [x] Update "Collection" and Delete event listeners to count how many Pokemon in data.entries and update value in p tag. 
- [x] Fix bugs
- **Clean Up**
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
