### ISSUE TITLE
User can generate a random Pokemon  #2

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/pokemon-catcher#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can generate a random Pokemon if they don't know any Pokemon.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the search page, the user can click on a "Generate Random Pokemon" button. Once clicked, a new page showing a random Pokemon will appear with all of it's stats.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/141197032-b466fbf9-7dea-41de-93d3-bc9d89d2e5cc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Query Dom for Generate Random Pokemon button
- [x] Add click event listener for Generate Random Button
- [x]  Concatenate a random number variable to Pokemon Api link
- [x] Hide search page and display new page with random pokemon image with it's stats
- **Clean Up**
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
