### ISSUE TITLE
User can add Pokemon to collection #3

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/pokemon-catcher#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add the Pokemon on the screen to their own personal collection.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The result page will display a "Add To Collection" button. If user clicks this button, a new page will be displayed showing their personal collection with the selected Pokemon added in.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/141355388-a8dde388-e660-48da-bfd8-980c0f5fd832.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Query Dom for "Add to Collection" button.  Add click Event Listener to save Pokemon and all of it's info into an object.
- [x] Push object into data object in main.js
- [x] Create result page with CSS applied
- [x] Show all saved entries in collection page
- [x] Query Dom for the "Collection" anchor tag in the header and add a click event listener. Once clicked, the collection page will be displayed.
- [x] If there are no saved Pokemon in Collection, a text notification will appear.
- **Clean Up**
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
