### ISSUE TITLE
User can view Pokemon #4

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/pokemon-catcher#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view Pokemon to see it's stats.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the collection page, each Pokemon will have a "View" button attached to it. When clicked, a new page will be displayed showing the Pokemon in a bigger resolution along with all of it's stats.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/141358763-98408808-eed9-47eb-99ff-4f8d0c5447c6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add Cursor: pointer to CSS when user hovers over "View" button
- [x] Query Dom for "View" button. Add click event listener. Once clicked, display search result page with the selected Pokemon.
- [x] Display "Back to Collection" button at bottom left.
- [x] Query Dom for 'Back to Collection' button and add click event Listener to go back to the collection page.
- **Clean Up**
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
