### ISSUE TITLE
User can delete Pokemon from collection #5

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/pokemon-catcher#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a Pokemon from their collection

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the collection page, each Pokemon entry has a "Delete" button. If clicked, the page will display a confirmation modal asking the user if they want to delete or cancel the request. If user clicks chooses to delete, the page will display their updated collection page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/141407519-66e8bad4-f408-4d68-ba53-9f22a5f39c43.png)
![image](https://user-images.githubusercontent.com/90541276/141407556-62edd318-a9b7-44dc-89a0-af53dc076faf.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a confirmation modal that goes over collection page with Cancel and Delete buttons.
- [x] Style confirmation modal in CSS for both mobile and desktop
- [x] Use event delegation for Delete button and add event listener to display confirmation modal once Delete button is clicked.
- [x] Add event listener to Cancel button to return back to collection page.
- [x] Add event listener to Delete button and remove Pokemon entry in collection.
- [x] If all Pokemon are deleted, notification should appear without reloading.
- **Clean Up**
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
